# One-Hot Encoding with many categories in a feature

In [2]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df=pd.read_csv('mercedes.csv',usecols=["X0","X1","X2","X3","X4","X5","X6"])
df.head()

   X0 X1  X2 X3 X4 X5 X6
0   k  v  at  a  d  u  j
1   k  t  av  e  d  y  l
2  az  w   n  c  d  x  j
3  az  t   n  f  d  x  l
4  az  v   n  f  d  h  d

In [4]:
for i in df.columns:
    print(len(df[i].unique()))

47
27
44
7
4
29
12

In [5]:
df.X1.value_counts().sort_values(ascending = False).head(10)

X1
aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
Name: count, dtype: int64

In [6]:
lst_10=df.X1.value_counts().sort_values(ascending = False).head(10).index
lst_10=list(lst_10)

In [7]:
lst_10

['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

In [8]:
for categories in lst_10:
    df[categories]=np.where(df['X1']==categories,1,0)

In [9]:
lst_10.append('X1')

In [10]:
df[lst_10]

      aa  s  b  l  v  r  i  a  c  o X1
0      0  0  0  0  1  0  0  0  0  0  v
1      0  0  0  0  0  0  0  0  0  0  t
2      0  0  0  0  0  0  0  0  0  0  w
3      0  0  0  0  0  0  0  0  0  0  t
4      0  0  0  0  1  0  0  0  0  0  v
...   .. .. .. .. .. .. .. .. .. .. ..
4204   0  1  0  0  0  0  0  0  0  0  s
4205   0  0  0  0  0  0  0  0  0  1  o
4206   0  0  0  0  1  0  0  0  0  0  v
4207   0  0  0  0  0  1  0  0  0  0  r
4208   0  0  0  0  0  1  0  0  0  0  r

[4209 rows x 11 columns]

### so basically this technique was used in KDD championship orange one where the grp was having to many categorical features and to encode them they have use ansy one hot encoder or something instead what they did wa s to select top 10 promissing feature and ecode the whole data accordinglu other all the data was skipped

# Ordinal number encoding

In [11]:
import datetime

In [12]:
today_date = datetime.datetime.today()

In [13]:
today_date

datetime.datetime(2025, 10, 27, 15, 13, 26, 250168)

In [14]:
today_date-datetime.timedelta(3)

datetime.datetime(2025, 10, 24, 15, 13, 26, 250168)

In [15]:
#### list comphrehension
days=[today_date-datetime.timedelta(x)for x in range (0,15)]

In [16]:
data=pd.DataFrame(days)
data.columns=["Day"]

In [17]:
data.head()

                         Day
0 2025-10-27 15:13:26.250168
1 2025-10-26 15:13:26.250168
2 2025-10-25 15:13:26.250168
3 2025-10-24 15:13:26.250168
4 2025-10-23 15:13:26.250168

In [18]:
data['Weekday']=data['Day'].dt.day_name()

In [19]:
data['Weekday'].unique()

array(['Monday', 'Sunday', 'Saturday', 'Friday', 'Thursday', 'Wednesday',
       'Tuesday'], dtype=object)

In [20]:
dictionary = {'Saturday':6, 'Friday':5, 'Thursday':4, 'Wednesday':3, 'Tuesday':2, 'Monday':1,'Sunday':7}

In [21]:
data['weekday_ordinal'] =data['Weekday'].map(dictionary)

In [22]:
data

                          Day    Weekday  weekday_ordinal
0  2025-10-27 15:13:26.250168     Monday                1
1  2025-10-26 15:13:26.250168     Sunday                7
2  2025-10-25 15:13:26.250168   Saturday                6
3  2025-10-24 15:13:26.250168     Friday                5
4  2025-10-23 15:13:26.250168   Thursday                4
5  2025-10-22 15:13:26.250168  Wednesday                3
6  2025-10-21 15:13:26.250168    Tuesday                2
7  2025-10-20 15:13:26.250168     Monday                1
8  2025-10-19 15:13:26.250168     Sunday                7
9  2025-10-18 15:13:26.250168   Saturday                6
10 2025-10-17 15:13:26.250168     Friday                5
11 2025-10-16 15:13:26.250168   Thursday                4
12 2025-10-15 15:13:26.250168  Wednesday                3
13 2025-10-14 15:13:26.250168    Tuesday                2
14 2025-10-13 15:13:26.250168     Monday                1

# count or frequency Encoding

In [24]:
train_set = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data' , header = None,index_col=None)
train_set.head()

HTTPError: HTTP Error 504: Timeout while reading response from Server