# One-Hot Encoding with many categories in a feature

In [8]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
df=pd.read_csv('mercedes.csv',usecols=["X0","X1","X2","X3","X4","X5","X6"])
df.head()

   X0 X1  X2 X3 X4 X5 X6
0   k  v  at  a  d  u  j
1   k  t  av  e  d  y  l
2  az  w   n  c  d  x  j
3  az  t   n  f  d  x  l
4  az  v   n  f  d  h  d

In [10]:
for i in df.columns:
    print(len(df[i].unique()))

47
27
44
7
4
29
12

In [11]:
df.X1.value_counts().sort_values(ascending = False).head(10)

X1
aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
Name: count, dtype: int64

In [12]:
lst_10=df.X1.value_counts().sort_values(ascending = False).head(10).index
lst_10=list(lst_10)

In [13]:
lst_10

['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

In [14]:
for categories in lst_10:
    df[categories]=np.where(df['X1']==categories,1,0)

In [15]:
lst_10.append('X1')

In [16]:
df[lst_10]

      aa  s  b  l  v  r  i  a  c  o X1
0      0  0  0  0  1  0  0  0  0  0  v
1      0  0  0  0  0  0  0  0  0  0  t
2      0  0  0  0  0  0  0  0  0  0  w
3      0  0  0  0  0  0  0  0  0  0  t
4      0  0  0  0  1  0  0  0  0  0  v
...   .. .. .. .. .. .. .. .. .. .. ..
4204   0  1  0  0  0  0  0  0  0  0  s
4205   0  0  0  0  0  0  0  0  0  1  o
4206   0  0  0  0  1  0  0  0  0  0  v
4207   0  0  0  0  0  1  0  0  0  0  r
4208   0  0  0  0  0  1  0  0  0  0  r

[4209 rows x 11 columns]

### so basically this technique was used in KDD championship orange one where the grp was having to many categorical features and to encode them they have use ansy one hot encoder or something instead what they did wa s to select top 10 promissing feature and ecode the whole data accordinglu other all the data was skipped

# Ordinal number encoding

In [17]:
import datetime

In [18]:
today_date = datetime.datetime.today()

In [19]:
today_date

datetime.datetime(2025, 11, 10, 0, 58, 48, 839299)

In [20]:
today_date-datetime.timedelta(3)

datetime.datetime(2025, 11, 7, 0, 58, 48, 839299)

In [21]:
#### list comphrehension
days=[today_date-datetime.timedelta(x)for x in range (0,15)]

In [22]:
data=pd.DataFrame(days)
data.columns=["Day"]

In [23]:
data.head()

                         Day
0 2025-11-10 00:58:48.839299
1 2025-11-09 00:58:48.839299
2 2025-11-08 00:58:48.839299
3 2025-11-07 00:58:48.839299
4 2025-11-06 00:58:48.839299

In [24]:
data['Weekday']=data['Day'].dt.day_name()

In [25]:
data['Weekday'].unique()

array(['Monday', 'Sunday', 'Saturday', 'Friday', 'Thursday', 'Wednesday',
       'Tuesday'], dtype=object)

In [26]:
dictionary = {'Saturday':6, 'Friday':5, 'Thursday':4, 'Wednesday':3, 'Tuesday':2, 'Monday':1,'Sunday':7}

In [27]:
data['weekday_ordinal'] =data['Weekday'].map(dictionary)

In [28]:
data

                          Day    Weekday  weekday_ordinal
0  2025-11-10 00:58:48.839299     Monday                1
1  2025-11-09 00:58:48.839299     Sunday                7
2  2025-11-08 00:58:48.839299   Saturday                6
3  2025-11-07 00:58:48.839299     Friday                5
4  2025-11-06 00:58:48.839299   Thursday                4
5  2025-11-05 00:58:48.839299  Wednesday                3
6  2025-11-04 00:58:48.839299    Tuesday                2
7  2025-11-03 00:58:48.839299     Monday                1
8  2025-11-02 00:58:48.839299     Sunday                7
9  2025-11-01 00:58:48.839299   Saturday                6
10 2025-10-31 00:58:48.839299     Friday                5
11 2025-10-30 00:58:48.839299   Thursday                4
12 2025-10-29 00:58:48.839299  Wednesday                3
13 2025-10-28 00:58:48.839299    Tuesday                2
14 2025-10-27 00:58:48.839299     Monday                1

# count or frequency Encoding

In [29]:
train_set = pd.read_csv('https://archive.ics.uci.edu/static/public/2/data.csv' , header = None,index_col=None)
train_set.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
1,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
2,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
3,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
4,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K