# One-Hot Encoding with many categories in a feature

In [8]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
df=pd.read_csv('mercedes.csv',usecols=["X0","X1","X2","X3","X4","X5","X6"])
df.head()

   X0 X1  X2 X3 X4 X5 X6
0   k  v  at  a  d  u  j
1   k  t  av  e  d  y  l
2  az  w   n  c  d  x  j
3  az  t   n  f  d  x  l
4  az  v   n  f  d  h  d

In [10]:
for i in df.columns:
    print(len(df[i].unique()))

47
27
44
7
4
29
12

In [11]:
df.X1.value_counts().sort_values(ascending = False).head(10)

X1
aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
Name: count, dtype: int64

In [12]:
lst_10=df.X1.value_counts().sort_values(ascending = False).head(10).index
lst_10=list(lst_10)

In [13]:
lst_10

['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

In [14]:
for categories in lst_10:
    df[categories]=np.where(df['X1']==categories,1,0)

In [15]:
lst_10.append('X1')

In [16]:
df[lst_10]

      aa  s  b  l  v  r  i  a  c  o X1
0      0  0  0  0  1  0  0  0  0  0  v
1      0  0  0  0  0  0  0  0  0  0  t
2      0  0  0  0  0  0  0  0  0  0  w
3      0  0  0  0  0  0  0  0  0  0  t
4      0  0  0  0  1  0  0  0  0  0  v
...   .. .. .. .. .. .. .. .. .. .. ..
4204   0  1  0  0  0  0  0  0  0  0  s
4205   0  0  0  0  0  0  0  0  0  1  o
4206   0  0  0  0  1  0  0  0  0  0  v
4207   0  0  0  0  0  1  0  0  0  0  r
4208   0  0  0  0  0  1  0  0  0  0  r

[4209 rows x 11 columns]

### so basically this technique was used in KDD championship orange one where the grp was having to many categorical features and to encode them they have use ansy one hot encoder or something instead what they did wa s to select top 10 promissing feature and ecode the whole data accordinglu other all the data was skipped

# Ordinal number encoding

In [17]:
import datetime

In [18]:
today_date = datetime.datetime.today()

In [19]:
today_date

datetime.datetime(2025, 11, 10, 0, 58, 48, 839299)

In [20]:
today_date-datetime.timedelta(3)

datetime.datetime(2025, 11, 7, 0, 58, 48, 839299)

In [21]:
#### list comphrehension
days=[today_date-datetime.timedelta(x)for x in range (0,15)]

In [22]:
data=pd.DataFrame(days)
data.columns=["Day"]

In [23]:
data.head()

                         Day
0 2025-11-10 00:58:48.839299
1 2025-11-09 00:58:48.839299
2 2025-11-08 00:58:48.839299
3 2025-11-07 00:58:48.839299
4 2025-11-06 00:58:48.839299

In [24]:
data['Weekday']=data['Day'].dt.day_name()

In [25]:
data['Weekday'].unique()

array(['Monday', 'Sunday', 'Saturday', 'Friday', 'Thursday', 'Wednesday',
       'Tuesday'], dtype=object)

In [26]:
dictionary = {'Saturday':6, 'Friday':5, 'Thursday':4, 'Wednesday':3, 'Tuesday':2, 'Monday':1,'Sunday':7}

In [27]:
data['weekday_ordinal'] =data['Weekday'].map(dictionary)

In [28]:
data

                          Day    Weekday  weekday_ordinal
0  2025-11-10 00:58:48.839299     Monday                1
1  2025-11-09 00:58:48.839299     Sunday                7
2  2025-11-08 00:58:48.839299   Saturday                6
3  2025-11-07 00:58:48.839299     Friday                5
4  2025-11-06 00:58:48.839299   Thursday                4
5  2025-11-05 00:58:48.839299  Wednesday                3
6  2025-11-04 00:58:48.839299    Tuesday                2
7  2025-11-03 00:58:48.839299     Monday                1
8  2025-11-02 00:58:48.839299     Sunday                7
9  2025-11-01 00:58:48.839299   Saturday                6
10 2025-10-31 00:58:48.839299     Friday                5
11 2025-10-30 00:58:48.839299   Thursday                4
12 2025-10-29 00:58:48.839299  Wednesday                3
13 2025-10-28 00:58:48.839299    Tuesday                2
14 2025-10-27 00:58:48.839299     Monday                1

# count or frequency Encoding

In [79]:
train_set = pd.read_csv('https://archive.ics.uci.edu/static/public/2/data.csv' , header = None,index_col=None)
train_set.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
1,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
2,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
3,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
4,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K

In [80]:
train_set.drop(0, inplace=True)

In [81]:
train_set.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
1,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
2,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
3,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
4,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
5,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [82]:
columns=[1,3,5,6,7,8,9,13]
train_set=train_set[columns]
train_set.columns=['Employment','degree','marital-status','designation','family_job','race','sex','country']

In [83]:
train_set.head()

,Employment,degree,marital-status,designation,family_job,race,sex,country
1,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States
2,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States
3,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States
4,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States
5,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba

In [84]:
for features in train_set.columns[:]:
    print(features,':',train_set[features].nunique(),'labels')

Employment : 9 labels
degree : 16 labels
marital-status : 7 labels
designation : 15 labels
family_job : 6 labels
race : 5 labels
sex : 2 labels
country : 42 labels

In [85]:
country_map=train_set['country'].value_counts().to_dict()

#### here we can see that actually there is the case of same frequency

In [89]:
df_cols=pd.DataFrame(country_map.items(),columns=['country','count'])

In [90]:
df_cols.head()

         country  count
0  United-States  43832
1         Mexico    951
2              ?    583
3    Philippines    295
4        Germany    206

In [92]:
df_cols.shape

(42, 2)

In [93]:
df_cols['country'].nunique()

42

In [95]:
df_cols['count'].nunique()

38

In [98]:
duplicate_rows=df_cols[df_cols['count'].duplicated(keep=False)]
duplicate_rows

                       country  count
25                      Greece     49
26                   Nicaragua     49
31                    Thailand     30
32                        Hong     30
35  Outlying-US(Guam-USVI-etc)     23
36                        Laos     23
37                  Yugoslavia     23

In [99]:
train_set['country']=train_set['country'].map(country_map)
train_set.head()

,Employment,degree,marital-status,designation,family_job,race,sex,country
1,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,43832.0
2,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,43832.0
3,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,43832.0
4,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,43832.0
5,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,138.0

#### Advantages 
1) easy 
2) we are not increasing the feature space

#### Disadvantage
1) it will provide the same frequency count or weight if the frequencies are same

# Target guided Ordinal Encoding
1. ordering the labels according to target
2. replace the labels by the joint probability of being 1 or 0

In [101]:
df=pd.read_csv('titanic.csv',usecols=['Cabin','Survived'])
df.head()

   Survived Cabin
0         0   NaN
1         1   C85
2         1   NaN
3         1  C123
4         0   NaN

In [102]:
df['Cabin'].fillna('Missing',inplace=True)

In [106]:
df['Cabin']=df['Cabin'].astype(str).str[0]

In [107]:
df.head()

   Survived Cabin
0         0     M
1         1     C
2         1     M
3         1     C
4         0     M

In [108]:
df.Cabin.unique()

array(['M', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [109]:
df.groupby(['Cabin'])['Survived'].mean()

Cabin
A    0.466667
B    0.744681
C    0.593220
D    0.757576
E    0.750000
F    0.615385
G    0.500000
M    0.299854
T    0.000000
Name: Survived, dtype: float64

In [110]:
df.groupby(['Cabin'])['Survived'].mean().sort_values().index

Index(['T', 'M', 'A', 'G', 'C', 'F', 'B', 'E', 'D'], dtype='object', name='Cabin')

In [112]:
ordinal_lables=df.groupby(['Cabin'])['Survived'].mean().sort_values().index
ordinal_lables

Index(['T', 'M', 'A', 'G', 'C', 'F', 'B', 'E', 'D'], dtype='object', name='Cabin')

In [113]:
enumerate(ordinal_lables,0)

In [114]:
ordinal_lables2={k:i for i,k in enumerate(ordinal_lables,0)}
ordinal_lables2

{'T': 0, 'M': 1, 'A': 2, 'G': 3, 'C': 4, 'F': 5, 'B': 6, 'E': 7, 'D': 8}

In [115]:
df['Cabin_ordinal_labels']=df['Cabin'].map(ordinal_lables2)
df.head()

   Survived Cabin  Cabin_ordinal_labels
0         0     M                     1
1         1     C                     4
2         1     M                     1
3         1     C                     4
4         0     M                     1

# Mean Encoding

In [116]:
mean_ordinal=df.groupby(['Cabin'])['Survived'].mean().to_dict()

In [117]:
mean_ordinal

{'A': 0.4666666666666667,
 'B': 0.7446808510638298,
 'C': 0.5932203389830508,
 'D': 0.7575757575757576,
 'E': 0.75,
 'F': 0.6153846153846154,
 'G': 0.5,
 'M': 0.29985443959243085,
 'T': 0.0}

In [118]:
df['mean_ordinal_encode']=df['Cabin'].map(mean_ordinal)
df.head()

   Survived Cabin  Cabin_ordinal_labels  mean_ordinal_encode
0         0     M                     1             0.299854
1         1     C                     4             0.593220
2         1     M                     1             0.299854
3         1     C                     4             0.593220
4         0     M                     1             0.299854

#### Disadvantage
1. High Risk of Overfitting
2. Needs Smoothing