In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline

import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_predict

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import cross_val_score

In [2]:
df_a = pd.read_csv('Agrotis ipsilon.csv')
df_a.head()

,id,uuid,observed_on_string,observed_on,time_observed_at,time_zone,user_id,user_login,user_name,created_at,...,taxon_geoprivacy,coordinates_obscured,positioning_method,positioning_device,place_country_name,species_guess,scientific_name,common_name,iconic_taxon_name,taxon_id
0,184262236,3ced98bb-5cd2-48af-8e2f-1195c565ff53,2023/09/21 05:42,2023-09-21,2023-09-21 03:42:00 UTC,Rome,1609913,giuseppe_molinari,Giuseppe Molinari,2023-09-21 14:40:05 UTC,...,NaN,False,NaN,NaN,Italy,Nottua dei seminati,Agrotis ipsilon,Ipsilon Dart Moth,Insecta,126276
1,184441399,9f4b3283-9d3a-417e-85b1-b9a30c871756,2023/09/22 00:00,2023-09-22,2023-09-21 22:00:00 UTC,Rome,350029,andreagrossi,Andrea Grossi,2023-09-22 21:32:19 UTC,...,NaN,False,NaN,NaN,Italy,Nottua dei seminati,Agrotis ipsilon,Ipsilon Dart Moth,Insecta,126276
2,184928006,ed8a2ef9-7bac-4a24-a94e-d385e0cfdb29,2023-09-25 22:10:38,2023-09-25,2023-09-25 20:10:38 UTC,Rome,392309,bac_77,Marco Crivellari,2023-09-25 21:47:22 UTC,...,NaN,False,gps,gps,Italy,Nottua dei seminati,Agrotis ipsilon,Ipsilon Dart Moth,Insecta,126276
3,185957180,946ed089-1dbb-491b-b779-8795b38a60c2,2023-10-02 22:46:58,2023-10-02,2023-10-02 20:46:58 UTC,Rome,392309,bac_77,Marco Crivellari,2023-10-02 21:01:33 UTC,...,NaN,False,gps,gps,Italy,Nottua dei seminati,Agrotis ipsilon,Ipsilon Dart Moth,Insecta,126276
4,186071926,20f3ac1c-ac9f-4b74-b89e-5615357aa009,2023-10-03 20:48:08,2023-10-03,2023-10-03 18:48:08 UTC,Rome,392309,bac_77,Marco Crivellari,2023-10-03 19:03:02 UTC,...,NaN,False,gps,gps,Italy,Nottua dei seminati,Agrotis ipsilon,Ipsilon Dart Moth,Insecta,126276

In [3]:
df_b = pd.read_csv('Aphids.csv')

In [4]:
df_c = pd.read_csv('Helicoverpa armigera.csv')

In [5]:
df_d = pd.read_csv('Nezara viridula.csv')

In [6]:
df_e = pd.read_csv('philaenus spumarius.csv')

In [7]:
df_g = pd.read_csv('Plutella xylostella.csv')

In [8]:
df_h = pd.read_csv('Spodoptera exigua.csv')

In [9]:
df_i = pd.read_csv('Sternorrhyncha.csv')

In [10]:
df_j = pd.read_csv('thrips.csv')

In [11]:
df_k = pd.read_csv('whitefly.csv')

In [12]:
df_final = pd.concat([df_a,df_b,df_c,df_d,df_e,df_g,df_h,df_i,df_j,df_k],axis=0,ignore_index=True)
df_final.head()

,id,uuid,observed_on_string,observed_on,time_observed_at,time_zone,user_id,user_login,user_name,created_at,...,taxon_geoprivacy,coordinates_obscured,positioning_method,positioning_device,place_country_name,species_guess,scientific_name,common_name,iconic_taxon_name,taxon_id
0,184262236,3ced98bb-5cd2-48af-8e2f-1195c565ff53,2023/09/21 05:42,2023-09-21,2023-09-21 03:42:00 UTC,Rome,1609913,giuseppe_molinari,Giuseppe Molinari,2023-09-21 14:40:05 UTC,...,NaN,False,NaN,NaN,Italy,Nottua dei seminati,Agrotis ipsilon,Ipsilon Dart Moth,Insecta,126276
1,184441399,9f4b3283-9d3a-417e-85b1-b9a30c871756,2023/09/22 00:00,2023-09-22,2023-09-21 22:00:00 UTC,Rome,350029,andreagrossi,Andrea Grossi,2023-09-22 21:32:19 UTC,...,NaN,False,NaN,NaN,Italy,Nottua dei seminati,Agrotis ipsilon,Ipsilon Dart Moth,Insecta,126276
2,184928006,ed8a2ef9-7bac-4a24-a94e-d385e0cfdb29,2023-09-25 22:10:38,2023-09-25,2023-09-25 20:10:38 UTC,Rome,392309,bac_77,Marco Crivellari,2023-09-25 21:47:22 UTC,...,NaN,False,gps,gps,Italy,Nottua dei seminati,Agrotis ipsilon,Ipsilon Dart Moth,Insecta,126276
3,185957180,946ed089-1dbb-491b-b779-8795b38a60c2,2023-10-02 22:46:58,2023-10-02,2023-10-02 20:46:58 UTC,Rome,392309,bac_77,Marco Crivellari,2023-10-02 21:01:33 UTC,...,NaN,False,gps,gps,Italy,Nottua dei seminati,Agrotis ipsilon,Ipsilon Dart Moth,Insecta,126276
4,186071926,20f3ac1c-ac9f-4b74-b89e-5615357aa009,2023-10-03 20:48:08,2023-10-03,2023-10-03 18:48:08 UTC,Rome,392309,bac_77,Marco Crivellari,2023-10-03 19:03:02 UTC,...,NaN,False,gps,gps,Italy,Nottua dei seminati,Agrotis ipsilon,Ipsilon Dart Moth,Insecta,126276

In [13]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10088 entries, 0 to 10087
Data columns (total 41 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                10088 non-null  int64
 1   uuid                              10088 non-null  object
 2   observed_on_string                10088 non-null  object
 3   observed_on                       10088 non-null  object
 4   time_observed_at                  9696 non-null   object
 5   time_zone                         10088 non-null  object
 6   user_id                           10088 non-null  int64
 7   user_login                        10088 non-null  object
 8   user_name                         7340 non-null   object
 9   created_at                        10088 non-null  object
 10  updated_at                        10088 non-null  object
 11  quality_grade                     10088 non-null  object
 12  license                           7227 non-null   object
 13  url                               10088 non-null  object
 14  image_url                         10088 non-null  object
 15  sound_url                         0 non-null      float64
 16  tag_list                          393 non-null    object
 17  description                       1255 non-null   object
 18  num_identification_agreements     10088 non-null  int64
 19  num_identification_disagreements  10088 non-null  int64
 20  captive_cultivated                10088 non-null  bool
 21  oauth_application_id              7458 non-null   float64
 22  place_guess                       10085 non-null  object
 23  latitude                          10088 non-null  float64
 24  longitude                         10088 non-null  float64
 25  positional_accuracy               7625 non-null   float64
 26  private_place_guess               0 non-null      float64
 27  private_latitude                  0 non-null      float64
 28  private_longitude                 0 non-null      float64
 29  public_positional_accuracy        7678 non-null   float64
 30  geoprivacy                        387 non-null    object
 31  taxon_geoprivacy                  0 non-null      float64
 32  coordinates_obscured              10088 non-null  bool
 33  positioning_method                3871 non-null   object
 34  positioning_device                3871 non-null   object
 35  place_country_name                10088 non-null  object
 36  species_guess                     9284 non-null   object
 37  scientific_name                   10088 non-null  object
 38  common_name                       8422 non-null   object
 39  iconic_taxon_name                 10088 non-null  object
 40  taxon_id                          10088 non-null  int64
dtypes: bool(2), float64(10), int64(5), object(24)
memory usage: 3.0+ MB

In [14]:
df_final.isnull().sum()

id                                      0
uuid                                    0
observed_on_string                      0
observed_on                             0
time_observed_at                      392
time_zone                               0
user_id                                 0
user_login                              0
user_name                            2748
created_at                              0
updated_at                              0
quality_grade                           0
license                              2861
url                                     0
image_url                               0
sound_url                           10088
tag_list                             9695
description                          8833
num_identification_agreements           0
num_identification_disagreements        0
captive_cultivated                      0
oauth_application_id                 2630
place_guess                             3
latitude                                0
longitude                               0
positional_accuracy                  2463
private_place_guess                 10088
private_latitude                    10088
private_longitude                   10088
public_positional_accuracy           2410
geoprivacy                           9701
taxon_geoprivacy                    10088
coordinates_obscured                    0
positioning_method                   6217
positioning_device                   6217
place_country_name                      0
species_guess                         804
scientific_name                         0
common_name                          1666
iconic_taxon_name                       0
taxon_id                                0
dtype: int64

In [15]:
df_final.drop(columns=['id','uuid','observed_on_string','time_observed_at','user_id','user_login','user_name','created_at','updated_at','quality_grade','license','url','image_url','sound_url','tag_list','description','num_identification_agreements','num_identification_disagreements','oauth_application_id','place_guess','positional_accuracy','private_place_guess','private_latitude','private_longitude','public_positional_accuracy','geoprivacy','taxon_geoprivacy','coordinates_obscured','positioning_method','positioning_device','species_guess','iconic_taxon_name',],inplace=True)

In [16]:
df_final.head()

,observed_on,time_zone,captive_cultivated,latitude,longitude,place_country_name,scientific_name,common_name,taxon_id
0,2023-09-21,Rome,False,43.597891,12.230247,Italy,Agrotis ipsilon,Ipsilon Dart Moth,126276
1,2023-09-22,Rome,False,44.833513,11.461343,Italy,Agrotis ipsilon,Ipsilon Dart Moth,126276
2,2023-09-25,Rome,False,44.883389,12.232362,Italy,Agrotis ipsilon,Ipsilon Dart Moth,126276
3,2023-10-02,Rome,False,44.883423,12.232209,Italy,Agrotis ipsilon,Ipsilon Dart Moth,126276
4,2023-10-03,Rome,False,44.880592,12.243348,Italy,Agrotis ipsilon,Ipsilon Dart Moth,126276

In [17]:
df_final.drop(columns=['time_zone','captive_cultivated','taxon_id'],inplace=True)

In [18]:
df_final.head()

,observed_on,latitude,longitude,place_country_name,scientific_name,common_name
0,2023-09-21,43.597891,12.230247,Italy,Agrotis ipsilon,Ipsilon Dart Moth
1,2023-09-22,44.833513,11.461343,Italy,Agrotis ipsilon,Ipsilon Dart Moth
2,2023-09-25,44.883389,12.232362,Italy,Agrotis ipsilon,Ipsilon Dart Moth
3,2023-10-02,44.883423,12.232209,Italy,Agrotis ipsilon,Ipsilon Dart Moth
4,2023-10-03,44.880592,12.243348,Italy,Agrotis ipsilon,Ipsilon Dart Moth

In [19]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10088 entries, 0 to 10087
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   observed_on         10088 non-null  object
 1   latitude            10088 non-null  float64
 2   longitude           10088 non-null  float64
 3   place_country_name  10088 non-null  object
 4   scientific_name     10088 non-null  object
 5   common_name         8422 non-null   object
dtypes: float64(2), object(4)
memory usage: 473.0+ KB

In [20]:
df_final['Day'] = df_final['observed_on'].apply(
    lambda x: x.split("/")[1] if "/" in x else x.split("-")[2]
).astype(int)

df_final['Month'] = df_final['observed_on'].apply(
    lambda x: x.split("/")[0] if "/" in x else x.split("-")[1]
).astype(int)

df_final['Year'] = df_final['observed_on'].apply(
    lambda x: x.split("/")[2] if "/" in x else x.split("-")[0]
).astype(int)

In [21]:
df_final.head()

,observed_on,latitude,longitude,place_country_name,scientific_name,common_name,Day,Month,Year
0,2023-09-21,43.597891,12.230247,Italy,Agrotis ipsilon,Ipsilon Dart Moth,21,9,2023
1,2023-09-22,44.833513,11.461343,Italy,Agrotis ipsilon,Ipsilon Dart Moth,22,9,2023
2,2023-09-25,44.883389,12.232362,Italy,Agrotis ipsilon,Ipsilon Dart Moth,25,9,2023
3,2023-10-02,44.883423,12.232209,Italy,Agrotis ipsilon,Ipsilon Dart Moth,2,10,2023
4,2023-10-03,44.880592,12.243348,Italy,Agrotis ipsilon,Ipsilon Dart Moth,3,10,2023

In [22]:
df_final.drop(columns=['observed_on'],inplace=True)

In [13]:
import ee
import pandas as pd
from tqdm import tqdm
import numpy as np

# Initialize Earth Engine
ee.Initialize(project='flowering-472417')

# ==========================
# Load dataset
# ==========================
df = pd.read_csv("final_dataset.csv")
df["date"] = pd.to_datetime(df[["Year", "Month", "Day"]])

# ==========================
# ERA5 dataset
# ==========================
era5 = ee.ImageCollection("ECMWF/ERA5/DAILY")

def get_weather_for_day(date, points):
    """Fetch climate for all points in one date (batch)"""
    start = ee.Date(date.strftime("%Y-%m-%d"))
    end = start.advance(1, "day")

    # Select ERA5 bands
    era5_day = era5.filterDate(start, end)
    if era5_day.size().getInfo() == 0:
        return pd.DataFrame()  # No data for this date

    img = era5_day.first().select([
        "minimum_2m_air_temperature",
        "maximum_2m_air_temperature",
        "dewpoint_temperature_2m",
        "total_precipitation"
    ])

    # Build FeatureCollection from points
    features = []
    for _, r in points.iterrows():
        point = ee.Geometry.Point([r["longitude"], r["latitude"]])
        features.append(ee.Feature(point, {
            "latitude": float(r["latitude"]),
            "longitude": float(r["longitude"]),
            "date": date.strftime("%Y-%m-%d")
        }))
    fc = ee.FeatureCollection(features)

    # Sample all points in one request
    sampled = img.sampleRegions(
        collection=fc,
        scale=10000,
        geometries=False
    ).getInfo()

    # Convert to pandas DataFrame
    records = []
    for f in sampled["features"]:
        props = f["properties"]
        records.append(props)
    return pd.DataFrame(records)

# ==========================
# Process in batches (by date)
# ==========================
all_weather = []
for date, group in tqdm(df.groupby("date"), desc="Fetching weather (batch)"):
    try:
        batch_df = get_weather_for_day(date, group)
        if not batch_df.empty:
            all_weather.append(batch_df)
    except Exception as e:
        print(f"⚠️ Skipping {date}: {e}")

# Combine all results
weather_df = pd.concat(all_weather, ignore_index=True)

# Merge back with original dataset
final_df = pd.merge(df, weather_df, on=["latitude", "longitude", "date"], how="left")

# Save locally
final_df.to_csv("dataset_with_weather.csv", index=False)
print("✅ Saved dataset_with_weather.csv")

Fetching weather (batch): 100%|██████████| 688/688 [05:56<00:00,  1.93it/s]

ValueError: No objects to concatenate

In [24]:
df_final.head()

,latitude,longitude,place_country_name,scientific_name,common_name,Day,Month,Year
0,43.597891,12.230247,Italy,Agrotis ipsilon,Ipsilon Dart Moth,21,9,2023
1,44.833513,11.461343,Italy,Agrotis ipsilon,Ipsilon Dart Moth,22,9,2023
2,44.883389,12.232362,Italy,Agrotis ipsilon,Ipsilon Dart Moth,25,9,2023
3,44.883423,12.232209,Italy,Agrotis ipsilon,Ipsilon Dart Moth,2,10,2023
4,44.880592,12.243348,Italy,Agrotis ipsilon,Ipsilon Dart Moth,3,10,2023

In [25]:
df_final.to_csv("final_dataset.csv", index=False)