In [143]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline 

import requests
from datetime import datetime, timedelta
import math
from tqdm import tqdm

In [144]:
df=pd.read_csv('global_crop_pests_last_2_years.csv')
df.head()

,species,observation_id,observed_on,latitude,longitude,event_date,place_guess,observer,quality_grade,created_at,updated_at,description,photo_url
0,Helicoverpa armigera,315037948,9/17/2025,46.970628,15.353309,8/17/2025,"Graz-Umgebung, Österreich",liebocher_natur,needs_id,2025-09-19T18:18:31+02:00,2025-09-19T18:21:54+02:00,NaN,https://inaturalist-open-data.s3.amazonaws.com...
1,Helicoverpa armigera,315035694,9/19/2025,54.935795,43.342560,8/17/2025,"Саров, Нижегородская обл., Россия",kosma2015,needs_id,2025-09-19T19:07:21+03:00,2025-09-19T19:07:28+03:00,NaN,https://inaturalist-open-data.s3.amazonaws.com...
2,Helicoverpa armigera,315035319,9/16/2025,42.689594,3.032577,8/17/2025,"Le Grand Large, 66140 Canet-en-Roussillon, France",gilles9191,needs_id,2025-09-19T18:05:28+02:00,2025-09-19T18:05:28+02:00,NaN,https://inaturalist-open-data.s3.amazonaws.com...
3,Helicoverpa armigera,315034131,9/19/2025,45.080336,7.651236,8/17/2025,"Campidoglio, Torino TO, Italia",ivan_di_gia,needs_id,2025-09-19T17:59:32+02:00,2025-09-19T17:59:32+02:00,NaN,https://inaturalist-open-data.s3.amazonaws.com...
4,Helicoverpa armigera,315033304,9/19/2025,46.628689,23.532357,8/17/2025,"Cluj, RO",dab37,research,2025-09-19T18:55:48+03:00,2025-09-19T18:57:27+03:00,NaN,https://inaturalist-open-data.s3.amazonaws.com...

In [145]:
df.shape

(82685, 13)

In [146]:
df_two = pd.read_csv('left_pest.csv')
df_two.head()

,species,observation_id,observed_on,latitude,longitude,event_date,place_guess,observer,quality_grade,created_at,updated_at,description,photo_url
0,Spodoptera exigua,314982847,2025-09-18,42.131839,25.310319,2025-08-17,"4292 Dobri dol, Bulgaria",stevem4560,research,2025-09-19T14:05:14+03:00,2025-09-19T18:56:59+03:00,UVA F15W / 350BL-T8\nWaning Crescent 9.9%\n3km...,https://inaturalist-open-data.s3.amazonaws.com...
1,Spodoptera exigua,314972405,2025-09-19,45.164724,6.883603,2025-08-17,"Torino, Piemonte, IT",max_65,needs_id,2025-09-19T11:28:58+02:00,2025-09-19T11:29:04+02:00,NaN,https://static.inaturalist.org/photos/56894682...
2,Spodoptera exigua,314971607,2025-09-19,40.182464,-8.554375,2025-08-17,"3150 Arzila, Portugal",scirpaceus,needs_id,2025-09-19T10:21:29+01:00,2025-09-19T10:21:29+01:00,Estação Paul de Arzila,https://static.inaturalist.org/photos/56893905...
3,Spodoptera exigua,314961759,2025-09-17,37.747071,-122.128795,2025-08-17,"Bemis St., Oakland",semirelicta,needs_id,2025-09-19T00:48:50-07:00,2025-09-19T00:48:50-07:00,NaN,https://static.inaturalist.org/photos/56892652...
4,Spodoptera exigua,314957298,2025-08-30,31.731255,35.009080,2025-08-17,זנוח2,shlomi_levi,research,2025-09-19T09:59:50+03:00,2025-09-19T10:48:31+03:00,NaN,https://inaturalist-open-data.s3.amazonaws.com...

In [147]:
df_two.shape

(23772, 13)

In [148]:
df_final = pd.concat([df,df_two],axis=0,ignore_index=True)
df_final.head()

,species,observation_id,observed_on,latitude,longitude,event_date,place_guess,observer,quality_grade,created_at,updated_at,description,photo_url
0,Helicoverpa armigera,315037948,9/17/2025,46.970628,15.353309,8/17/2025,"Graz-Umgebung, Österreich",liebocher_natur,needs_id,2025-09-19T18:18:31+02:00,2025-09-19T18:21:54+02:00,NaN,https://inaturalist-open-data.s3.amazonaws.com...
1,Helicoverpa armigera,315035694,9/19/2025,54.935795,43.342560,8/17/2025,"Саров, Нижегородская обл., Россия",kosma2015,needs_id,2025-09-19T19:07:21+03:00,2025-09-19T19:07:28+03:00,NaN,https://inaturalist-open-data.s3.amazonaws.com...
2,Helicoverpa armigera,315035319,9/16/2025,42.689594,3.032577,8/17/2025,"Le Grand Large, 66140 Canet-en-Roussillon, France",gilles9191,needs_id,2025-09-19T18:05:28+02:00,2025-09-19T18:05:28+02:00,NaN,https://inaturalist-open-data.s3.amazonaws.com...
3,Helicoverpa armigera,315034131,9/19/2025,45.080336,7.651236,8/17/2025,"Campidoglio, Torino TO, Italia",ivan_di_gia,needs_id,2025-09-19T17:59:32+02:00,2025-09-19T17:59:32+02:00,NaN,https://inaturalist-open-data.s3.amazonaws.com...
4,Helicoverpa armigera,315033304,9/19/2025,46.628689,23.532357,8/17/2025,"Cluj, RO",dab37,research,2025-09-19T18:55:48+03:00,2025-09-19T18:57:27+03:00,NaN,https://inaturalist-open-data.s3.amazonaws.com...

In [149]:
df_final.shape

(106457, 13)

In [150]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106457 entries, 0 to 106456
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   species         106457 non-null  object
 1   observation_id  106457 non-null  int64
 2   observed_on     106457 non-null  object
 3   latitude        105625 non-null  float64
 4   longitude       105625 non-null  float64
 5   event_date      106457 non-null  object
 6   place_guess     105404 non-null  object
 7   observer        106457 non-null  object
 8   quality_grade   106457 non-null  object
 9   created_at      106457 non-null  object
 10  updated_at      106457 non-null  object
 11  description     9496 non-null    object
 12  photo_url       106235 non-null  object
dtypes: float64(2), int64(1), object(10)
memory usage: 10.6+ MB

In [151]:
df_final['species'].unique()

array(['Helicoverpa armigera', 'Bemisia tabaci', 'Tetranychus urticae',
       'Plutella xylostella', 'Spodoptera litura', 'Tribolium castaneum',
       'Myzus persicae', 'Spodoptera frugiperda', 'Aphis gossypii',
       'Nilaparvata lugens', 'Locusta migratoria', 'Popillia japonica',
       'Lygus lineolaris', 'Phyllotreta cruciferae', 'Agrotis ipsilon',
       'Acrida exaltata', 'Agonoscelis nubilis', 'Aloa lactinea',
       'Archips micaceana', 'Atractomorpha crenulata',
       'Callitettix versicolor', 'Chaetocnema pulicaria',
       'Chilo partellus', 'Cletus punctiger', 'Creatonotos gangis',
       'Euproctis similis', 'Eyprepocnemis alacris', 'Helicoverpa zea',
       'Spodoptera exigua', 'Cnaphalocrocis medinalis',
       'Pyrilla perpusilla', 'Nezara viridula', 'Mocis frugalis',
       'Mythimna separata', 'Sitophilus oryzae', 'Sogatella furcifera',
       'Leptocorisa acuta', 'Scirpophaga incertulas',
       'Corcyra cephalonica', 'Dicladispa armigera', 'Menida versicolor',
       'Oedaleus senegalensis', 'Schistocerca gregaria', 'Oxya hyla'],
      dtype=object)

In [152]:
# Get species counts in descending order
species_counts = df_final['species'].value_counts()

print(species_counts)

species
Helicoverpa armigera        10000
Plutella xylostella         10000
Popillia japonica           10000
Agrotis ipsilon             10000
Nezara viridula             10000
Spodoptera frugiperda        9264
Lygus lineolaris             9103
Helicoverpa zea              6915
Spodoptera exigua            4474
Spodoptera litura            4008
Locusta migratoria           3742
Euproctis similis            3300
Cnaphalocrocis medinalis     2192
Mocis frugalis               1638
Leptocorisa acuta            1330
Scirpophaga incertulas       1305
Aphis gossypii               1257
Creatonotos gangis           1029
Sitophilus oryzae             989
Aloa lactinea                 806
Atractomorpha crenulata       722
Callitettix versicolor        663
Tetranychus urticae           662
Schistocerca gregaria         550
Mythimna separata             515
Cletus punctiger              463
Myzus persicae                415
Oxya hyla                     405
Sogatella furcifera           158
Oedaleus senegalensis         106
Menida versicolor              85
Tribolium castaneum            70
Archips micaceana              61
Bemisia tabaci                 56
Phyllotreta cruciferae         37
Eyprepocnemis alacris          33
Nilaparvata lugens             28
Chilo partellus                27
Agonoscelis nubilis            16
Corcyra cephalonica            13
Pyrilla perpusilla             11
Acrida exaltata                 5
Chaetocnema pulicaria           3
Dicladispa armigera             1
Name: count, dtype: int64

In [153]:
df_final.sort_values(by=[''])

KeyError: ''

In [ ]:
df_tu = df_final[df_final['species'] == 'Tetranychus urticae']


print(df_tu)

                   species  observation_id observed_on   latitude   longitude  \
10056  Tetranychus urticae       314923636   9/18/2025  34.042428 -118.470597
10057  Tetranychus urticae       314638411   9/17/2025  29.638353  -82.361105
10058  Tetranychus urticae       314627026   9/17/2025  47.636847 -117.412425
10059  Tetranychus urticae       314414214   9/14/2025  46.708080 -123.988156
10060  Tetranychus urticae       314397609   9/16/2025  49.162457   16.886775
...                    ...             ...         ...        ...         ...
10713  Tetranychus urticae       184876823   9/25/2023  51.539740   -1.738014
10714  Tetranychus urticae       184767570   9/23/2023  47.752065   11.739407
10715  Tetranychus urticae       184436190   9/22/2023  21.401028 -157.804348
10716  Tetranychus urticae       184246314   9/21/2023  51.718749   36.133349
10717  Tetranychus urticae       184187588   9/20/2023  43.404859  -79.692951

      event_date                           place_guess      observer  \
10056  8/17/2025  S Carmelina Ave, Los Angeles, CA, US     adaman797
10057  8/17/2025          Hull Rd, Gainesville, FL, US     tommyevic
10058  8/17/2025              Manito, Spokane, WA, USA  iguanaiguana
10059  8/17/2025          Fisher Ave, Tokeland, WA, US       dnfrank
10060  8/17/2025          684 01 Slavkov u Brna, Česko     pavelsink
...          ...                                   ...           ...
10713  8/17/2025  Belcombe Close, Swindon, England, GB          owed
10714  8/17/2025     83703 Gmund am Tegernsee, Germany        kemper
10715  8/17/2025                Kaneohe, HI 96744, USA      beamerla
10716  8/17/2025   Курск, Курская обл., Россия, 305005    mikami-kun
10717  8/17/2025                           Ontario, CA   randomrandy

      quality_grade                 created_at                 updated_at  \
10056      needs_id  2025-09-18T18:49:49-07:00  2025-09-18T18:49:50-07:00
10057      needs_id  2025-09-17T15:29:04-04:00  2025-09-19T11:42:53-04:00
10058      needs_id  2025-09-17T11:25:03-07:00  2025-09-17T11:25:18-07:00
10059      needs_id  2025-09-16T12:45:23-07:00  2025-09-16T12:46:30-07:00
10060      needs_id  2025-09-16T20:18:55+02:00  2025-09-16T20:18:55+02:00
...             ...                        ...                        ...
10713      needs_id  2023-09-25T16:48:58+01:00  2023-09-25T16:50:57+01:00
10714      needs_id  2023-09-24T23:33:04+02:00  2023-09-24T23:33:04+02:00
10715      needs_id  2023-09-22T10:51:38-10:00  2023-09-22T10:51:46-10:00
10716      needs_id  2023-09-21T15:22:13+03:00  2023-09-21T15:22:27+03:00
10717      needs_id  2023-09-20T19:09:37-04:00  2023-09-20T19:09:47-04:00

            description                                          photo_url
10056               NaN  https://static.inaturalist.org/photos/56885081...
10057               NaN  https://static.inaturalist.org/photos/56905526...
10058               NaN  https://static.inaturalist.org/photos/56827630...
10059               NaN  https://inaturalist-open-data.s3.amazonaws.com...
10060  ex *Tagetes* sp.  https://inaturalist-open-data.s3.amazonaws.com...
...                 ...                                                ...
10713               NaN  https://inaturalist-open-data.s3.amazonaws.com...
10714               NaN  https://inaturalist-open-data.s3.amazonaws.com...
10715               NaN  https://inaturalist-open-data.s3.amazonaws.com...
10716               NaN  https://inaturalist-open-data.s3.amazonaws.com...
10717               NaN  https://inaturalist-open-data.s3.amazonaws.com...

[662 rows x 13 columns]

In [ ]:
common_name_dict = {
    "Helicoverpa armigera": "Cotton bollworm, Corn earworm, Old World bollworm",
    "Bemisia tabaci": "Silverleaf whitefly, Sweet potato whitefly, Cotton whitefly",
    "Tetranychus urticae": "Twospotted spider mite",
    "Plutella xylostella": "Diamondback moth, Cabbage moth",
    "Spodoptera litura": "Tobacco cutworm, Cotton leafworm",
    "Tribolium castaneum": "Red flour beetle",
    "Myzus persicae": "Green peach aphid",
    "Spodoptera frugiperda": "Fall armyworm",
    "Aphis gossypii": "Cotton aphid",
    "Nilaparvata lugens": "Brown planthopper",
    "Locusta migratoria": "Migratory locust",
    "Popillia japonica": "Japanese beetle",
    "Lygus lineolaris": "Tarnished plant bug",
    "Phyllotreta cruciferae": "Flea beetle",
    "Agrotis ipsilon": "Black cutworm",
    "Acrida exaltata": "Grasshopper",
    "Agonoscelis nubilis": "Brown plant hopper",
    "Aloa lactinea": "Whitefly",
    "Archips micaceana": "Lesser appleworm",
    "Atractomorpha crenulata": "Grasshopper",
    "Callitettix versicolor": "Leafhopper",
    "Chaetocnema pulicaria": "Flea beetle",
    "Chilo partellus": "Stalk borer",
    "Cletus punctiger": "Longhorned beetle",
    "Creatonotos gangis": "Lonomia moth",
    "Euproctis similis": "Lonomia moth",
    "Eyprepocnemis alacris": "Grasshopper",
    "Helicoverpa zea": "Corn earworm",
    "Spodoptera exigua": "Beet armyworm",
    "Cnaphalocrocis medinalis": "Rice leaf folder",
    "Pyrilla perpusilla": "Pyrilla",
    "Nezara viridula": "Green stink bug",
    "Mocis frugalis": "Grass webworm",
    "Mythimna separata": "Armyworm",
    "Sitophilus oryzae": "Rice weevil",
    "Sogatella furcifera": "Whitebacked planthopper",
    "Leptocorisa acuta": "Rice bug",
    "Scirpophaga incertulas": "Yellow stem borer",
    "Corcyra cephalonica": "Rice moth",
    "Dicladispa armigera": "Citrus beetle",
    "Menida versicolor": "Leafhopper",
    "Oedaleus senegalensis": "Grasshopper",
    "Schistocerca gregaria": "Desert locust",
    "Oxya hyla": "Grasshopper"
}
df_final["common_name"] = df_final["species"].map(common_name_dict)
df_final.head()

,species,observation_id,observed_on,latitude,longitude,event_date,observer,quality_grade,created_at,updated_at,common_name
0,Helicoverpa armigera,315037948,9/17/2025,46.970628,15.353309,8/17/2025,liebocher_natur,needs_id,2025-09-19T18:18:31+02:00,2025-09-19T18:21:54+02:00,"Cotton bollworm, Corn earworm, Old World bollworm"
1,Helicoverpa armigera,315035694,9/19/2025,54.935795,43.342560,8/17/2025,kosma2015,needs_id,2025-09-19T19:07:21+03:00,2025-09-19T19:07:28+03:00,"Cotton bollworm, Corn earworm, Old World bollworm"
2,Helicoverpa armigera,315035319,9/16/2025,42.689594,3.032577,8/17/2025,gilles9191,needs_id,2025-09-19T18:05:28+02:00,2025-09-19T18:05:28+02:00,"Cotton bollworm, Corn earworm, Old World bollworm"
3,Helicoverpa armigera,315034131,9/19/2025,45.080336,7.651236,8/17/2025,ivan_di_gia,needs_id,2025-09-19T17:59:32+02:00,2025-09-19T17:59:32+02:00,"Cotton bollworm, Corn earworm, Old World bollworm"
4,Helicoverpa armigera,315033304,9/19/2025,46.628689,23.532357,8/17/2025,dab37,research,2025-09-19T18:55:48+03:00,2025-09-19T18:57:27+03:00,"Cotton bollworm, Corn earworm, Old World bollworm"

In [ ]:
df_final.isnull().sum()

species               0
observation_id        0
observed_on           0
latitude            832
longitude           832
event_date            0
place_guess        1053
observer              0
quality_grade         0
created_at            0
updated_at            0
description       96961
photo_url           222
common_name           0
dtype: int64

In [ ]:
df_final.drop(columns=['observation_id','observed_on','observer','quality_grade','created_at','updated_at'], inplace=True)

In [ ]:
df_final.drop(columns=['place_guess','description','photo_url'], inplace=True)

In [ ]:
df_final.head()

                species   latitude  longitude event_date
0  Helicoverpa armigera  46.970628  15.353309  8/17/2025
1  Helicoverpa armigera  54.935795  43.342560  8/17/2025
2  Helicoverpa armigera  42.689594   3.032577  8/17/2025
3  Helicoverpa armigera  45.080336   7.651236  8/17/2025
4  Helicoverpa armigera  46.628689  23.532357  8/17/2025

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106457 entries, 0 to 106456
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   species     106457 non-null  object
 1   latitude    105625 non-null  float64
 2   longitude   105625 non-null  float64
 3   event_date  106457 non-null  object
dtypes: float64(2), object(2)
memory usage: 3.2+ MB

In [ ]:
df_final['Day'] = df_final['event_date'].apply(
    lambda x: x.split("/")[1] if "/" in x else x.split("-")[2]
).astype(int)

df_final['Month'] = df_final['event_date'].apply(
    lambda x: x.split("/")[0] if "/" in x else x.split("-")[1]
).astype(int)

df_final['Year'] = df_final['event_date'].apply(
    lambda x: x.split("/")[2] if "/" in x else x.split("-")[0]
).astype(int)

In [ ]:
df_final.drop(columns=['event_date'],inplace=True)

In [ ]:
df_final.head()

                species   latitude  longitude  Day  Month  Year
0  Helicoverpa armigera  46.970628  15.353309   17      8  2025
1  Helicoverpa armigera  54.935795  43.342560   17      8  2025
2  Helicoverpa armigera  42.689594   3.032577   17      8  2025
3  Helicoverpa armigera  45.080336   7.651236   17      8  2025
4  Helicoverpa armigera  46.628689  23.532357   17      8  2025

In [ ]:


def fetch_weather_nasa(lat, lon, year, month, day, base_temp=10):
    """
    Fetches daily weather data from NASA POWER API and adds
    - VPD (Vapour Pressure Deficit)
    - GDD (Growing Degree Days)
    - Season (calendar-based)
    """
    date_str = f"{year}{month:02d}{day:02d}"
    url = (
        f"https://power.larc.nasa.gov/api/temporal/daily/point?"
        f"start={date_str}&end={date_str}"
        f"&latitude={lat}&longitude={lon}"
        "&parameters=T2M_MIN,T2M_MAX,T2M,PRECTOTCORR,WS10M,WD10M,ALLSKY_SFC_SW_DWN,RH2M"
        "&community=AG"
        "&format=JSON"
    )

    try:
        r = requests.get(url, timeout=10)
        r.raise_for_status()
        data = r.json()
    except Exception:
        return None

    properties = data.get("properties", {}).get("parameter", {})
    if not properties:
        return None  # No data for this date/location

    # ----------------- Step 1: Extract core weather variables -----------------
    tmin = list(properties.get("T2M_MIN", {}).values())[0] if properties.get("T2M_MIN") else np.nan
    tmax = list(properties.get("T2M_MAX", {}).values())[0] if properties.get("T2M_MAX") else np.nan
    tmean = list(properties.get("T2M", {}).values())[0] if properties.get("T2M") else np.nan
    rh_mean = list(properties.get("RH2M", {}).values())[0] if properties.get("RH2M") else np.nan

    result = {
        "tmin": tmin,
        "tmax": tmax,
        "tmean": tmean,
        "precipitation": list(properties.get("PRECTOTCORR", {}).values())[0] if properties.get("PRECTOTCORR") else np.nan,
        "wind_speed": list(properties.get("WS10M", {}).values())[0] if properties.get("WS10M") else np.nan,
        "wind_dir": list(properties.get("WD10M", {}).values())[0] if properties.get("WD10M") else np.nan,
        "solar_radiation": list(properties.get("ALLSKY_SFC_SW_DWN", {}).values())[0] if properties.get("ALLSKY_SFC_SW_DWN") else np.nan,
        "rh_mean": rh_mean,
    }

    # ----------------- Step 2: Derived Biological Indicators -----------------
    # (a) Vapour Pressure Deficit (VPD)
    if not np.isnan(tmean) and not np.isnan(rh_mean):
        es = 0.6108 * math.exp((17.27 * tmean) / (tmean + 237.3))  # Saturation vapor pressure (kPa)
        ea = es * rh_mean / 100  # Actual vapor pressure
        result["vpd"] = round(es - ea, 3)
    else:
        result["vpd"] = np.nan

    # (b) Growing Degree Days (GDD)
    if not np.isnan(tmin) and not np.isnan(tmax):
        gdd = max(((tmax + tmin) / 2) - base_temp, 0)
        result["gdd"] = round(gdd, 2)
    else:
        result["gdd"] = np.nan

    # ----------------- Step 3: Season Classification -----------------
    # Simple meteorological season (based on hemisphere)
    northern = lat >= 0
    if northern:
        if month in [12, 1, 2]:
            season = "Winter"
        elif month in [3, 4, 5]:
            season = "Spring"
        elif month in [6, 7, 8]:
            season = "Summer"
        else:
            season = "Autumn"
    else:
        if month in [12, 1, 2]:
            season = "Summer"
        elif month in [3, 4, 5]:
            season = "Autumn"
        elif month in [6, 7, 8]:
            season = "Winter"
        else:
            season = "Spring"

    result["season"] = season

    return result

In [ ]:
df_final[df_final['Day']==]

SyntaxError: invalid syntax (4117575787.py, line 1)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106457 entries, 0 to 106456
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   species          106457 non-null  object
 1   latitude         105625 non-null  float64
 2   longitude        105625 non-null  float64
 3   Day              106457 non-null  int64
 4   Month            106457 non-null  int64
 5   Year             106457 non-null  int64
 6   tmin             1751 non-null    float64
 7   tmax             1751 non-null    float64
 8   tmean            1751 non-null    float64
 9   precipitation    1751 non-null    float64
 10  wind_speed       1751 non-null    float64
 11  wind_dir         1751 non-null    float64
 12  sunshine_hours   1751 non-null    float64
 13  solar_radiation  1751 non-null    float64
 14  et0              1751 non-null    float64
 15  rh_mean          1751 non-null    float64
 16  vpd              1751 non-null    float64
 17  date             106457 non-null  datetime64[ns]
 18  key              106457 non-null  object
dtypes: datetime64[ns](1), float64(13), int64(3), object(2)
memory usage: 15.4+ MB

In [ ]:
df_final.isnull().sum()

species                 0
latitude              832
longitude             832
Day                     0
Month                   0
Year                    0
tmin               104706
tmax               104706
tmean              104706
precipitation      104706
wind_speed         104706
wind_dir           104706
sunshine_hours     104706
solar_radiation    104706
et0                104706
rh_mean            104706
vpd                104706
date                    0
key                     0
dtype: int64